{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ag2s.cronet",
    "module": "okhttp-kt",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "okhttp",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-kt-0.0.1.aar",
          "url": "okhttp-kt-0.0.1.aar",
          "size": 7042,
          "sha512": "baa5168b60266b157263f462345f4c8c858b9df7cad4586c28378dca3ee93da1669de9004caf33cbb977ad1e74479781a9a6ae419e8d45670c7697535c17aab9",
          "sha256": "f0f04945f91628c73e848529d21675b87e813ce426a93b4cb878c46c8e4f5246",
          "sha1": "ad132f91491088d06f2badd870f4b6eb75cf8811",
          "md5": "e034215e36153f6f3a49cf0173cc6ab7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.ag2s.cronet",
          "module": "okhttp",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-kt-0.0.1.aar",
          "url": "okhttp-kt-0.0.1.aar",
          "size": 7042,
          "sha512": "baa5168b60266b157263f462345f4c8c858b9df7cad4586c28378dca3ee93da1669de9004caf33cbb977ad1e74479781a9a6ae419e8d45670c7697535c17aab9",
          "sha256": "f0f04945f91628c73e848529d21675b87e813ce426a93b4cb878c46c8e4f5246",
          "sha1": "ad132f91491088d06f2badd870f4b6eb75cf8811",
          "md5": "e034215e36153f6f3a49cf0173cc6ab7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-kt-0.0.1-sources.jar",
          "url": "okhttp-kt-0.0.1-sources.jar",
          "size": 1574,
          "sha512": "370efe9faacff3f346f82280f9c1dcb765b63c977eec7c56bc5e786e0ab3bcb21d820690b5414fd015cfa25cbd410086f053adec48cb49296e95d346dd706f21",
          "sha256": "e1dff2edb511deb64b4e08d32b2bdb6b94abf35aae7bc5dc1728668f0fec9085",
          "sha1": "5831d9d9bf1ae851a1f3f82ae3ab5a1b190d8aa1",
          "md5": "ce30d131567cfe3a8dcbbfa18b51cd06"
        }
      ]
    }
  ]
}
